refactor: move ci setup to unique file
WIP use global ci setup actions

WIP use global ci setup in releaser

WIP remove pre commit git lfs

WIP remove git attributes

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -46,17 +46,21 @@ jobs:
         # Snyk can be used to break the build when it detects security issues.
         # In this case we want to upload the SAST issues to GitHub Code Scanning
         uses: snyk/actions/setup@d406fd286b663eb8c6f8adcced4f7bcd199c0a3f
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+          # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+          # Use || true to not fail the pipeline
+        #
         # For Snyk Open Source you must first set up the development environment for your application's dependencies
         # For example for Node
         #- uses: actions/setup-node@v3
         #  with:
         #    node-version: 16
         # This is where you will need to introduce the Snyk API token created with your Snyk account
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-          # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-          # Use || true to not fail the pipeline
       - name: login to snyk
+        # - uses: ./.github/actions/ci-setup
+        #   name: Setup CI environment
+
         run: snyk auth ${{ secrets.SNYK_TOKEN }}
       - name: Snyk Code test
         run: snyk code test --sarif > snyk-code.sarif  || true
